-- 事件
local EventNames = {}

EventNames.CHARACTOR_HP = "EventNames.CHARACTOR_HP"
EventNames.STATUS_STATE = "EventNames.STATUS_STATE"
EventNames.GAME_STATE = "EventNames.GAME_STATE"
EventNames.MSG_PROTO = "EventNames.MSG_PROTO"

EventNames.NET_CONNECT = "EventNames.NET_CONNECT"
EventNames.NET_DISCONNECT = "EventNames.NET_DISCONNECT"

EventNames.BATTLE_PLAYER_CHANGE = "EventNames.BATTLE_PLAYER_CHANGE"
EventNames.BATTLE_CAMERA_MOVE = "EventNames.BATTLE_CAMERA_MOVE"
EventNames.BATTLE_PLAYER_MOVE = "EventNames.BATTLE_PLAYER_MOVE"
EventNames.BATTLE_PLAYER_ATTACK = "EventNames.BATTLE_PLAYER_ATTACK"
EventNames.BATTLE_PLAYER_RELOAD = "EventNames.BATTLE_PLAYER_RELOAD"
EventNames.BATTLE_ENEMY_HURT = "EventNames.BATTLE_ENEMY_HURT"
EventNames.BATTLE_ENEMY_DIE = "EventNames.BATTLE_ENEMY_DIE"
EventNames.BATTLE_ENEMY_NUM = "EventNames.BATTLE_ENEMY_NUM"
EventNames.BATTLE_ENEMY_HEADSHOT = "EventNames.BATTLE_ENEMY_HEADSHOT"
EventNames.BATTLE_ENEMY_CREATE = "EventNames.BATTLE_ENEMY_CREATE"
EventNames.BATTLE_PLAYER_HP = "EventNames.BATTLE_PLAYER_HP"
EventNames.BATTLE_CHARACTOR_DIE = "EventNames.BATTLE_CHARACTOR_DIE"
EventNames.BATTLE_WEAPON_AIM = "EventNames.BATTLE_WEAPON_AIM"
EventNames.BATTLE_WEAPON_SHELL = "EventNames.BATTLE_WEAPON_SHELL"
EventNames.BATTLE_SHOW_SHELL = "EventNames.BATTLE_SHOW_SHELL"
EventNames.BATTLE_MAINUI_ENEMYNUM = "EventNames.BATTLE_MAINUI_ENEMYNUM"
EventNames.BATTLE_RESULT = "EventNames.BATTLE_RESULT"

LDeclare("EventNames", EventNames)

return EventNames